### ISSUE TITLE
Yo, can I join ur company ?

### ISSUE THREAD

**Issue by sonicx180** [Grey41/grey41.github.io#4]
The one you created for gaming. I'd like to join to get better at game dev. Thx!

**Comment by Grey41** [comment]
Hello! Are you talking about JoBase? If you’d like to start making games, and you have Python, you can install it with `pip install JoBase`. After that, I suggest you follow [this tutorial](https://jobase.org/tutorials/1).

Thank you for reaching out.
<hello@greyhope.uk>

**Comment by sonicx180** [comment]
I mean to Grey41 STudios
